### ISSUE TITLE
cohesity_uda_source module giving errors CohesityClient' is not defined

### ISSUE THREAD

**Issue by amhaats1** [cohesity/ansible-collection#30]
Cohesity cluster version 6.6.0d_u6
cohesity-management-sdk            1.8.1
Ansible Collection - cohesity.dataprotect 1.1.2
python 3.9

## 🐛 Bug Report
File "/tmp/ansible_cohesity_uda_source_payload_6_kr0jz_/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py", line 83, in get_cohesity_client
NameError: name 'CohesityClient' is not defined

## To Reproduce

Playbook:

  - hosts: localhost
    gather_facts: true
    become: false
    collections:
      - cohesity.dataprotect
    tasks:
      - name: "Create new Protection Source for UDB host"
        cohesity_uda_source:
            state: present
            cluster: "omaccohtestcls00.corp.mutualofomaha.com"
            username: "{{username}}"
            password: "{{password}}"
            validate_certs: false
            source_type: "DB2"
            os_type: "Linux"
            db_username: "{{dbusername}}"
            db_password: "{{dbpassword}}"
            hosts:
             - lx14602
            source_name: lx14602_angela_testing
            endpoint: lx14602
            scripts_dir: "/opt/cohesity/db2/scripts"
            source_registration_args: "--source-name=lx14602_angela_testing --db2profile-path=/data/insttest/sqllib/db2profile"

## Expected behavior

<!--
  How did you expect your project to behave? Register the source

I'm able to use the same credentials in module cohesity_source just fine  it just will not work with cohesity_uda_source
      cohesity_source:
        cluster: "omaccohtestcls00.corp.mutualofomaha.com"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: "false"
        state: present

## Actual Behavior
Error:
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_cohesity_uda_source_payload_6_kr0jz_/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py", line 83, in get_cohesity_client
NameError: name 'CohesityClient' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1685555932.2740078-58-160024015122544/AnsiballZ_cohesity_uda_source.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1685555932.2740078-58-160024015122544/AnsiballZ_cohesity_uda_source.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1685555932.2740078-58-160024015122544/AnsiballZ_cohesity_uda_source.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_source', init_globals=dict(_module_fqn='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_source', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cohesity_uda_source_payload_6_kr0jz_/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_source.py", line 433, in <module>
  File "/tmp/ansible_cohesity_uda_source_payload_6_kr0jz_/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_source.py", line 332, in main
  File "/tmp/ansible_cohesity_uda_source_payload_6_kr0jz_/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py", line 88, in get_cohesity_client
NameError: name 'raise__cohesity_exception__handler' is not defined
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\\n  File \\"/tmp/ansible_cohesity_uda_source_payload_6_kr0jz_/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\\", line 83, in get_cohesity_client\\nNameError: name 'CohesityClient' is not defined\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\"/root/.ansible/tmp/ansible-tmp-1685555932.2740078-58-160024015122544/AnsiballZ_cohesity_uda_source.py\\", line 107, in <module>\\n    _ansiballz_main()\\n  File \\"/root/.ansible/tmp/ansible-tmp-1685555932.2740078-58-160024015122544/AnsiballZ_cohesity_uda_source.py\\", line 99, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/root/.ansible/tmp/ansible-tmp-1685555932.2740078-58-160024015122544/AnsiballZ_cohesity_uda_source.py\\", line 47, in invoke_module\\n    runpy.run_module(mod_name='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_source', init_globals=dict(_module_fqn='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_source', _modlib_path=modlib_path),\\n  File \\"/usr/lib64/python3.9/runpy.py\\", line 225, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\"/usr/lib64/python3.9/runpy.py\\", line 97, in _run_module_code\\n    _run_code(code, mod_globals, init_globals,\\n  File \\"/usr/lib64/python3.9/runpy.py\\", line 87, in _run_code\\n    exec(code, run_globals)\\n  File \\"/tmp/ansible_cohesity_uda_source_payload_6_kr0jz_/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_source.py\\", line 433, in <module>\\n  File \\"/tmp/ansible_cohesity_uda_source_payload_6_kr0jz_/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_source.py\\", line 332, in main\\n  File \\"/tmp/ansible_cohesity_uda_source_payload_6_kr0jz_/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\\", line 88, in get_cohesity_client\\nNameError: name 'raise__cohesity_exception__handler' is not defined\\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error",
    "rc": 1

**Comment by naveena-maplelabs** [comment]
Will check and get back to you, thanks

**Comment by amhaats1** [comment]
Any updates?

**Comment by pyashish** [comment]
Sorry @amhaats1  we will have an update by EoW. Does the import of CohesityClient work with other playbooks ? Did you change any versions of sdk/cluster/ansible ?

**Comment by amhaats1** [comment]
Yes we are able to use cohesity_source module just fine
Example:
collections:
cohesity.dataprotect
tasks:
    - name: "Cohesity Protection Source: Register SQL Source"
      cohesity_source:
        cluster: "omaccohtestcls00.corp.mutualofomaha.com"
        username: "{{ generic_username }}"
        password: "{{ generic_password }}"
        validate_certs: "false"
        state: present
        environment: "SQL"
        endpoint: "{{ item }}"
      with_items: "{{ groups['sql'] }}"

**Comment by naveena-maplelabs** [comment]
@amhaats1 What is the ansible collection version you are using? Can you please try with the latest version 1.1.3 and let us know.

**Comment by amhaats1** [comment]
Ansible collection cohesity.dataprotect    1.1.3 
Cohesity cluster version 6.6.0d_u6
cohesity-management-sdk 1.8.1
python 3.9

Same error:

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_cohesity_uda_source_payload_4hi_ecr8/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py", line 83, in get_cohesity_client
NameError: name 'CohesityClient' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1690489208.9410808-20-230672701914302/AnsiballZ_cohesity_uda_source.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1690489208.9410808-20-230672701914302/AnsiballZ_cohesity_uda_source.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1690489208.9410808-20-230672701914302/AnsiballZ_cohesity_uda_source.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_source', init_globals=dict(_module_fqn='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_source', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cohesity_uda_source_payload_4hi_ecr8/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_source.py", line 433, in <module>
  File "/tmp/ansible_cohesity_uda_source_payload_4hi_ecr8/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_source.py", line 332, in main
  File "/tmp/ansible_cohesity_uda_source_payload_4hi_ecr8/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py", line 88, in get_cohesity_client
NameError: name 'raise__cohesity_exception__handler' is not defined
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_cohesity_uda_source_payload_4hi_ecr8/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\", line 83, in get_cohesity_client\nNameError: name 'CohesityClient' is not defined\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1690489208.9410808-20-230672701914302/AnsiballZ_cohesity_uda_source.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1690489208.9410808-20-230672701914302/AnsiballZ_cohesity_uda_source.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1690489208.9410808-20-230672701914302/AnsiballZ_cohesity_uda_source.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_source', init_globals=dict(_module_fqn='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_source', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cohesity_uda_source_payload_4hi_ecr8/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_source.py\", line 433, in <module>\n  File \"/tmp/ansible_cohesity_uda_source_payload_4hi_ecr8/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_source.py\", line 332, in main\n  File \"/tmp/ansible_cohesity_uda_source_payload_4hi_ecr8/ansible_cohesity_uda_source_payload.zip/ansible_collections/cohesity/dataprotect/plugins/module_utils/cohesity_hints.py\", line 88, in get_cohesity_client\nNameError: name 'raise__cohesity_exception__handler' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by naveena-maplelabs** [comment]
@amhaats1 With latest ansible collection 1.1.6 issue will be resolved, please feel free to reopen the issue if you face any issues.
