### ISSUE TITLE
Modules cohesity_uda_protection_group and cohesity_oracle_job No module named 'cohesity_management_sdk'

### ISSUE THREAD

**Issue by amhaats1** [cohesity/ansible-collection#31]
Cohesity cluster version 6.6.0d_u6
cohesity-management-sdk 1.8.1
Ansible Collection - cohesity.dataprotect 1.1.2
python 3.9

## 🐛 Bug Report

(A clear and concise description of what the bug is)

No module named 'cohesity_management_sdk'

We have the sdk installed and working with other modules but these 2 are having issues.
cohesity_uda_protection_group  
cohesity_oracle_job

## To Reproduce

(Write your steps here:)

Oracle EXAMPLE:
- hosts: localhost
  gather_facts: true
  become: true

  collections:
    - cohesity.dataprotect

# Update a Oracle Server Protection Group
  tasks:
    - name: "Update Protection Job"
      cohesity_oracle_job:
        cluster: "omaccohtestcls00.corp.mutualofomaha.com"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: "false"
        cancel_active: "true"
        state: absent
        name: "NP_ORA_RPO24H_50"
        endpoint: "lx14821"
        databases: 
          - "CDBT971"
        delete_backups: false

UDA/DB2 example:

- hosts: localhost
  gather_facts: true
  become: false

  collections:
    - cohesity.dataprotect
  tasks:
    - name: "Uda Create Protection job"
      cohesity_uda_protection_group:
        cluster: "omaccohtestcls00.corp.mutualofomaha.com"
        username: "{{username}}"
        password: "{{password}}"
        state: present
        protection_group_name: NP_UDB_lx14602_angela_test
        storage_domain: "Testcls00StorageDomain"
        policy: "NP_UDB_Mon_F_24H_20M_14D"
        endpoint: "lx14602"      
        objects:
          - udbtest1
        time_zone: "America/Chicago"
        start_time: "16:00"
        concurrency: 16
        log_backup_args: "--prune-logs-hours=1"

## Expected behavior

 update or create the Protection job
 

## Actual Behavior
cohesity_oracle_job

File "/tmp/ansible_cohesity_oracle_job_payload_2ebxu602/ansible_cohesity_oracle_job_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_oracle_job.py", line 158, in <module>
ModuleNotFoundError: No module named 'cohesity_management_sdk'

cohesity_uda_protection_group
 File "/tmp/ansible_cohesity_uda_protection_group_payload_jyp_ibj2/ansible_cohesity_uda_protection_group_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_protection_group.py", line 236, in <module>
ModuleNotFoundError: No module named 'cohesity_management_sdk'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1685559952.5219164-58-153271826074246/AnsiballZ_cohesity_uda_protection_group.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1685559952.5219164-58-153271826074246/AnsiballZ_cohesity_uda_protection_group.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1685559952.5219164-58-153271826074246/AnsiballZ_cohesity_uda_protection_group.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_protection_group', init_globals=dict(_module_fqn='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_protection_group', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cohesity_uda_protection_group_payload_jyp_ibj2/ansible_cohesity_uda_protection_group_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_protection_group.py\", line 236, in <module>\nModuleNotFoundError: No module named 'cohesity_management_sdk'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",

The cohesity_uda_protection_group points back to the sdk files not working correctly

cohesity_uda_protection_group.py

Starting at line 236 

from cohesity_management_sdk.exceptions.api_exception import APIException
from cohesity_management_sdk.models.delete_protection_job_param import (
    DeleteProtectionJobParam,
)
from cohesity_management_sdk.models.cancel_protection_job_run_param import (
    CancelProtectionJobRunParam,
)
from cohesity_management_sdk.models.run_protection_job_param import (
    RunProtectionJobParam,
)

Module: cohesity_oracle_job.py

Starting at line 158 

from cohesity_management_sdk.exceptions.api_exception import APIException
from cohesity_management_sdk.models.delete_protection_job_param import (
    DeleteProtectionJobParam,
)
from cohesity_management_sdk.models.cancel_protection_job_run_param import (
    CancelProtectionJobRunParam,
)
from cohesity_management_sdk.models.protection_job_request_body import (
    ProtectionJobRequestBody,
)
from cohesity_management_sdk.models.run_protection_job_param import (
    RunProtectionJobParam,
)
from cohesity_management_sdk.models.source_special_parameter import (
    SourceSpecialParameter,
)
from cohesity_management_sdk.models.oracle_special_parameters import (
    OracleSpecialParameters,
)
from cohesity_management_sdk.models.oracle_database_node_channel import (
    OracleDatabaseNodeChannel,
)
from cohesity_management_sdk.models.oracle_app_params import OracleAppParams

try:
    # => When unit testing, we need to look in the correct location however, when run via ansible,
    # => the expectation is that the modules will live under ansible.
    from ansible.module_utils.urls import urllib_error
    from ansible_collections.cohesity.dataprotect.plugins.module_utils.cohesity_utilities import (
        cohesity_common_argument_spec,
        raise__cohesity_exception__handler,
    )
    from ansible_collections.cohesity.dataprotect.plugins.module_utils.cohesity_hints import (
        get_cohesity_client,
    )

**Comment by naveena-maplelabs** [comment]
Will check and get back to you, thanks

**Comment by amhaats1** [comment]
Any updates?

**Comment by naveena-maplelabs** [comment]
@amhaats1 can you try ansible --version command once to check the python version used in the ansible.
![image](https://github.com/cohesity/ansible-collection/assets/62049303/55746cbb-01f3-42b2-8062-d2249c36f1f9)

**Comment by amhaats1** [comment]
upgraded to 1.1.3

Getting the following error:

<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1690489943.3138216-20-209172356501263/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1690489943.3138216-20-209172356501263/AnsiballZ_cohesity_uda_protection_group.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1690489943.3138216-20-209172356501263/AnsiballZ_cohesity_uda_protection_group.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1690489943.3138216-20-209172356501263/AnsiballZ_cohesity_uda_protection_group.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_protection_group', init_globals=dict(_module_fqn='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_protection_group', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cohesity_uda_protection_group_payload_y0pgwuw4/ansible_cohesity_uda_protection_group_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_protection_group.py", line 236, in <module>
ModuleNotFoundError: No module named 'cohesity_management_sdk'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1690489943.3138216-20-209172356501263/AnsiballZ_cohesity_uda_protection_group.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1690489943.3138216-20-209172356501263/AnsiballZ_cohesity_uda_protection_group.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1690489943.3138216-20-209172356501263/AnsiballZ_cohesity_uda_protection_group.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_protection_group', init_globals=dict(_module_fqn='ansible_collections.cohesity.dataprotect.plugins.modules.cohesity_uda_protection_group', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cohesity_uda_protection_group_payload_y0pgwuw4/ansible_cohesity_uda_protection_group_payload.zip/ansible_collections/cohesity/dataprotect/plugins/modules/cohesity_uda_protection_group.py\", line 236, in <module>\nModuleNotFoundError: No module named 'cohesity_management_sdk'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

Playbook as follows:
- hosts: localhost
  gather_facts: no
  become: false

  collections:
    - cohesity.dataprotect
  tasks:
    - name: "Uda Create Protection job"
      cohesity_uda_protection_group:
        cluster: "omaccohtestcls00.corp.mutualofomaha.com"
        username: "corp.mutualofomaha.com/{{ generic_username }}"
        password: "{{ generic_password }}"
        state: present
        protection_group_name: NP_UDB_lx15717_angela_test
        storage_domain: "Testcls00StorageDomain"
        policy: "NP_UDB_Mon_F_24H_20M_14D"
        endpoint: "lx15717"      
        objects:
          - udbtest1
        time_zone: "America/Chicago"
        start_time: "16:00"
        concurrency: 16
        log_backup_args: "--prune-logs-hours=1"

**Comment by naveena-maplelabs** [comment]
@amhaats1 With latest ansible collection 1.1.6 this issue will be resolved. Please feel free to reopen this ticket if the you face any issues.
